USE pictureManager;

CREATE TABLE USERS (
	ID nvarchar(50) PRIMARY KEY,
	NICK nvarchar(15) UNIQUE NOT NULL,
	PWD nvarchar(255) NOT NULL,
	NAME varchar(25) NOT NULL,
	ROLE NVARCHAR(25) NOT NULL
);

CREATE TABLE COMISION (
	ID int IDENTITY(1,1) PRIMARY KEY,
	NAME nvarchar(25),
	PHOTO image,
	DESCRIPTION text,
	ORDERCOMISION int,
	PRICE FLOAT
);

CREATE TABLE SESION (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(250),
	DESCRIPTION TEXT,
	IDPHOTO INT,
	DATESESION DATE,
	IDCOMISION int,
	FOREIGN KEY (IDCOMISION) REFERENCES COMISION(ID)
);

CREATE TABLE PHOTO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(25),
	PICTURE IMAGE,
	IDSESION INT,
	ORDERPHOTO INT,
	FOREIGN KEY (IDSESION) REFERENCES SESION(ID)
);

ALTER TABLE SESION ADD FOREIGN KEY (IDPHOTO) REFERENCES PHOTO(ID) ON DELETE CASCADE;

CREATE TABLE WORKER(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(30),
	CONTACT NVARCHAR(30),
	URLCONTACT NVARCHAR(255)
);

CREATE TABLE WORK (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(100)
)

CREATE TABLE SESION_WORKER(
	IDSESION INT,
	IDWORKER INT,
	IDWORK INT,
	PRIMARY KEY (IDSESION, IDWORKER),
	FOREIGN KEY (IDSESION) REFERENCES SESION(ID),
	FOREIGN KEY (IDWORKER) REFERENCES WORKER(ID),
	FOREIGN KEY (IDWORK) REFERENCES WORK(ID)
);

INSERT INTO USERS VALUES('hsyu?dcn7_81237$8n49t!12','ADMIN','root','Admin');

--PROCEDURES
GO
ALTER PROCEDURE GETLOGIN
(@NICK NVARCHAR(15), @PWD NVARCHAR(32))
AS
	
	SELECT COUNT(*) as EXISTE FROM USERS WHERE NICK LIKE @NICK AND PWD LIKE @PWD;
	
GO
