USE photo;

CREATE TABLE USERS (
ID int IDENTITY(1,1) PRIMARY KEY,
NICK nvarchar(15),
PWD nvarchar(255),
NAME varchar(25)
);

CREATE TABLE COMISION(
ID int IDENTITY(1,1) PRIMARY KEY,
NAME nvarchar(25),
PHOTO image,
DESCRIPTION text,
ORDERCOMISION int
);

CREATE TABLE SESION (
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(250),
DESCRIPTION TEXT,
IDPHOTO INT,
DATESESION DATE
);

CREATE TABLE PHOTO(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(25),
PICTURE IMAGE,
IDSESION INT,
ORDERPHOTO INT,
FOREIGN KEY (IDSESION) REFERENCES SESION(ID)
);

ALTER TABLE SESION ADD FOREIGN KEY (IDPHOTO) REFERENCES PHOTO(ID) ON DELETE CASCADE;

CREATE TABLE WORKER(
ID INT IDENTITY(1,1) PRIMARY KEY,
TYPE NVARCHAR(100),
NAME NVARCHAR(30) UNIQUE,
CONTACT NVARCHAR(30),
URLCONTACT NVARCHAR(255)
);

CREATE TABLE SESION_WORKER(
IDSESION INT,
IDWORKER INT,
PRIMARY KEY (IDSESION, IDWORKER),
FOREIGN KEY (IDSESION) REFERENCES SESION(ID),
FOREIGN KEY (IDWORKER) REFERENCES WORKER(ID)
);

