USE pictureManager;

CREATE TABLE USERS (
	ID nvarchar(50) PRIMARY KEY,
	NICK nvarchar(15) UNIQUE NOT NULL,
	PWD nvarchar(255) NOT NULL,
	NAME varchar(25) NOT NULL,
	ROLE NVARCHAR(25) NOT NULL
);

CREATE TABLE COMISION (
	ID int IDENTITY(1,1) PRIMARY KEY,
	NAME nvarchar(25),
	DESCRIPTION text,
	ORDERCOMISION int,
	PRICE FLOAT,
	PHOTO text,
);

CREATE TABLE SESION (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(250),
	DESCRIPTION TEXT,
	IDPHOTO INT,
	DATESESION DATE,
	IDCOMISION int,
	FOREIGN KEY (IDCOMISION) REFERENCES COMISION(ID)
);

CREATE TABLE PHOTO(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PICTURE NVARCHAR(50) PRIMARY KEY,
	IDSESION INT,
	ORDERPHOTO INT,
	FOREIGN KEY (IDSESION) REFERENCES SESION(ID) ON DELETE CASCADE
);

CREATE TABLE WORKER(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(30),
	CONTACT NVARCHAR(30),
	URLCONTACT NVARCHAR(255)
);

CREATE TABLE WORK (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME NVARCHAR(100)
)

CREATE TABLE SESION_WORKER(
	IDSESION INT,
	IDWORKER INT,
	IDWORK INT,
	PRIMARY KEY (IDSESION, IDWORKER),
	FOREIGN KEY (IDSESION) REFERENCES SESION(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDWORKER) REFERENCES WORKER(ID) ON DELETE CASCADE,
	FOREIGN KEY (IDWORK) REFERENCES WORK(ID) ON DELETE CASCADE
);

INSERT INTO USERS VALUES('hsyu?dcn7_81237$8n49t!12','ADMIN','root','Admin', 'ADMINISTRATOR');

-- PROCEDURES --

----+ TRABAJOS +----
CREATE PROCEDURE MOSTRARTRABAJOS
AS

    SELECT* FROM WORK;
GO

CREATE PROCEDURE ADDTRABAJO
(@NAME NVARCHAR(100))
AS
    INSERT INTO WORK VALUES(@NAME)
GO

CREATE PROCEDURE DELETETRABAJO
(@ID INT)
AS
    DELETE FROM WORK WHERE ID = @ID
GO
----+ +----

----+ Sesion +----
CREATE PROCEDURE INSERTSESION
(@NAME NVARCHAR(25), @DESCRIPTION TEXT, @DATE DATE, @IDCOMISION INT)
AS
	INSERT INTO SESION VALUES(@NAME,@DESCRIPTION,NULL,@DATE,@IDCOMISION)
GO

CREATE PROCEDURE GETSESION
AS
SELECT * FROM SESION;
GO

CREATE PROCEDURE DELETESESION
(@ID INT)
AS
DELETE FROM SESION WHERE ID = @ID;
GO

CREATE PROCEDURE GETSESIONID
(@ID INT)
AS
SELECT * FROM SESION WHERE ID = @ID;
GO

CREATE PROCEDURE GETPARTNERWORKBYSESION
(@ID INT)
AS
	SELECT sw.IDWORKER as IDPARTNER, p.NAME as PARTNER, sw.IDWORK as IDWORK, w.NAME as WORK
FROM SESION_WORKER sw
INNER JOIN SESION s
on s.ID =  sw.IDSESION
INNER JOIN WORK w
on w.ID = sw.IDWORK
INNER JOIN WORKER p
ON sw.IDWORKER = p.ID
WHERE s.ID = @ID;

GO

CREATE PROCEDURE ADDPARTNERWORKINTOSESION
(@IDSESION INT, @IDPARTER INT, @IDWORK INT)
AS
	INSERT INTO SESION_WORKER VALUES (@IDSESION,@IDPARTER,@IDWORK)
	
GO

CREATE PROCEDURE DELETEPARTERWORKFROMSESION
(@ID INT, @IDPARTNER INT, @IDWORK INT)
AS
DELETE FROM SESION_WORKER WHERE IDSESION = @ID AND IDWORKER = @IDPARTNER AND IDWORK = @IDWORK;
GO

CREATE PROCEDURE MODIFYSESION
(@ID INT, @NAME NVARCHAR(250), @DESCRIPTION TEXT, @DATESESION DATE, @IDCOMISION INT)
AS
UPDATE SESION 
SET NAME = @NAME, 
DESCRIPTION = @DESCRIPTION, 
DATESESION = @DATESESION, 
IDCOMISION = @IDCOMISION
WHERE ID = @ID
GO
----+ +----

----+ PHOTO +----
 CREATE PROCEDURE GETPHOTOS
(@IDSESION INT)
AS
	SELECT * FROM PHOTO
	WHERE IDSESION = @IDSESION
	ORDER BY ORDERPHOTO DESC;
GO

CREATE PROCEDURE INSERTPHOTO
(@NAMEPHOTO TEXT, @IDSESION INT)
AS
	DECLARE @NUM INT
	SELECT @NUM = COUNT(*) FROM PHOTO WHERE IDSESION = @IDSESION
	INSERT INTO PHOTO VALUES(@NAMEPHOTO,@IDSESION,@NUM)
GO

----+ +----

----+ Partner +----
CREATE PROCEDURE MOSTRARPARTICIPANTES
AS
	SELECT * FROM WORKER;
GO

CREATE PROCEDURE ADDPARTICIPANTE
(@NAME NVARCHAR(30), @CONTACT NVARCHAR(30), @URLCONTACT NVARCHAR(255))
AS
	INSERT INTO WORKER VALUES (@NAME, @CONTACT, @URLCONTACT)
GO

CREATE PROCEDURE DELETEPARTICIPANTE
(@ID INT)
AS
	DELETE FROM WORKER WHERE ID = @ID
GO

CREATE PROCEDURE UPDATEPARTICIPANTE
(@ID INT, @NAME NVARCHAR(30), @CONTACT NVARCHAR(30), @URLCONTACT NVARCHAR(30))
AS
	UPDATE WORKER
	SET NAME = @NAME, CONTACT = @CONTACT, URLCONTACT = @URLCONTACT
	WHERE ID = @ID
GO

----+ LOGIN +----
CREATE PROCEDURE GETUSER
(@NICK NVARCHAR(25), @PWD NVARCHAR(25))
AS
    SELECT *

    FROM USERS

    WHERE NICK LIKE @NICK

    AND PWD LIKE @PWD;
GO

----+ COMISION +----
 CREATE PROCEDURE INSERTCOMISION
(@NAME NVARCHAR(25), @DESCRIPTION TEXT, @PATH TEXT, @PRICE FLOAT)
AS
	DECLARE @ORDERCOMISION INT

	SELECT @ORDERCOMISION = COUNT(*) FROM COMISION

	SET @ORDERCOMISION = @ORDERCOMISION + 1

	INSERT INTO COMISION VALUES(@NAME,@DESCRIPTION, @ORDERCOMISION,@PRICE,@PATH)

GO

CREATE PROCEDURE GETCOMISIONS
AS
	SELECT * 
	FROM COMISION
	order by ORDERCOMISION;
GO 

CREATE PROCEDURE DELETECOMISION
(@ID INT)
AS
	DELETE FROM COMISION
	WHERE ID = @ID;
GO

    CREATE PROCEDURE MODIFYSESSION
(@ID INT, @NAME nvarchar(25), @PHOTO text, @DESCRIPTION TEXT, @PRICE float)
AS
	IF(@PHOTO IS NULL)
	BEGIN
		UPDATE COMISION
		SET NAME = @NAME,
		DESCRIPTION = @DESCRIPTION,
		PRICE = @PRICE
		WHERE ID = @ID;
	END
	ELSE
	BEGIN
		UPDATE COMISION
			SET NAME = @NAME,
			PHOTO = @PHOTO,
			DESCRIPTION = @DESCRIPTION,
			PRICE = @PRICE
			WHERE ID = @ID;
	END
GO

CREATE PROCEDURE MODIFYORDERCOMISION
(@ID INT, @ORDER INT)
AS
	UPDATE COMISION 
	SET ORDERCOMISION = @ORDER 
	WHERE ID = @ID;
GO