
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFotoMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SESION_WORKER
{

    public int IDSESION { get; set; }

    public int IDWORKER { get; set; }

    public Nullable<int> IDWORK { get; set; }



    public virtual SESION SESION { get; set; }

    public virtual WORKER WORKER { get; set; }

    public virtual WORK WORK { get; set; }

}

}
