
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoFotoMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SESION_WORKER
{

    public int IDSESION { get; set; }

    public int IDWORKER { get; set; }

    public Nullable<int> IDWORK { get; set; }



    public virtual SESION SESION { get; set; }

    public virtual WORKER WORKER { get; set; }

    public virtual WORK WORK { get; set; }

}

}
