
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RepositorioPictureManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PHOTO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PHOTO()
    {

        this.SESION1 = new HashSet<SESION>();

    }


    public int ID { get; set; }

    public string PICTURE { get; set; }

    public Nullable<int> IDSESION { get; set; }

    public Nullable<int> ORDERPHOTO { get; set; }



    public virtual SESION SESION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SESION> SESION1 { get; set; }

}

}
