
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RepositorioPictureManager.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SESION
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SESION()
    {

        this.PHOTO = new HashSet<PHOTO>();

        this.SESION_WORKER = new HashSet<SESION_WORKER>();

    }


    public int ID { get; set; }

    public string NAME { get; set; }

    public string DESCRIPTION { get; set; }

    public Nullable<int> IDPHOTO { get; set; }

    public Nullable<System.DateTime> DATESESION { get; set; }

    public Nullable<int> IDCOMISION { get; set; }



    public virtual COMISION COMISION { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHOTO> PHOTO { get; set; }

    public virtual PHOTO PHOTO1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SESION_WORKER> SESION_WORKER { get; set; }

}

}
