
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RepositorioPictureManager.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USERS
{

    public int ID { get; set; }
    [Required(ErrorMessage = "Debe de escribir un usuario")]
    public string NICK { get; set; }
    [Required(ErrorMessage = "Debe de escribir una contraseña")]
    public string PWD { get; set; }

    public string NAME { get; set; }

}

}
